/*** Function ID's for STris **************************************************/

#define STrisID                                                                 555
#define PrgAccel                                                                555
#define PrgIcon                                                                 555
#define PrgMenu                                                                 555


#define AboutDialog                                     16402
#define DLG_OPTIONS                              16403
#define ShowHiscoreDialog                               1002
#define HiscoreDialog                                   1003
#define EnterNameDialog                                 1004
#define TestDialog                                              1005
#define EnterName                                               1006
#define KeyDialog                                               1007

/*
#define Pieces16Bitmap                                  1001
#define Pieces24Bitmap                                  1002
*/
#define ToMBitmap                                                        16405
#define KeyLeftBitmap                                   1001
#define KeyRightBitmap                                  1002


#define OptionsHelpSubTablle    11002
#define OptionsHelpSubTable                     11002
#define AboutHelpSubTable                               11003
#define ShowHiscoreHelpSubTable 11004
#define EnterNameHelpSubTable   11005
#define KeyHelpSubTable                                 11006


#define PrgHelpSubTable                                 1000
#define PrgHelpTable                                    555
#define Help                                                                    555

#define IDD_HELP                                                                3001

#define IDD_ROTATE                                                              303
#define IDD_NR                                                                  1000
#define IDD_NAME                                                                1001
#define IDD_SCORE                                                               1002
#define IDD_LINES                                                               1003
#define IDD_LEVEL                                                               1004

#define IDD_PRGTITEL                                    500
#define IDD_AUTHORS                                                     501
#define IDD_COPYRIGHT                                   502
#define IDD_WARRANTY                                    503
#define IDD_DISTRIBUTION                                504

#define IDD_KEYLEFT                                                     510
#define IDD_KEYRIGHT                                    511
#define IDD_KEYROTATE                                   512
#define IDD_KEYROTATE2                                  513
#define IDD_KEYDROP                                                     514

#define IDD_TEXTLEFT                                    520
#define IDD_TEXTRIGHT                                   521
#define IDD_TEXTROTATE                                  522
#define IDD_TEXTROTATE2                                 523
#define IDD_TEXTDROP                                    524                                                     /* Never change order of these */

#define IDD_KEYTEXT1                                    525
#define IDD_KEYTEXT2                                    526


#define IDD_PALETTE                                     500
#define IDD_SOUND                                               300
#define IDD_GRID                                                301
#define IDD_NEXTPIECE                   302
#define IDD_SPEEDSLIDER                 400
#define IDD_LEVELSLIDER                 401
#define IDD_SPEEDTEXT                   402
#define IDD_LEVELTEXT                   403
#define IDD_REMAINPAUSED                404
#define IDD_SOLID                                               405
#define IDD_LINES1                                              136
#define IDD_LEVEL1                                              149
#define IDD_RANK1                                               101
#define IDD_NAME1                                               111
#define IDD_SCORE1                                              121
#define IDD_TEXT_FIELD                  200
#define IDD_HISCORETEXT                 2000
#define IDD_DEFAULT                                     2001

#define IDF_QUIT                                                16384
#define IDF_ABOUT                                               16385
#define IDF_HELP                                                16386

#define IDF_UNUSED                                              16387                                                   /* Function not yet implemented */

#define IDF_HISCORE                                     16388
#define IDF_NEW_GAME                    16389
#define IDF_PAUSE                                               16390
#define IDF_STATISTICS                  16391
#define IDF_OPTIONS                                     16392
#define IDF_TEST                                                16393
#define IDF_KEY                                                 16397
#define IDF_USINGHELP                   16399
#define IDF_HOWTOPLAY                   16400
#define IDF_KEYSHELP                    16401

#define IDF_PLAYFIELD                   16395
#define IDF_NEXT_PIECE                  16396



/*-------------------------------------------------------------*
*  Help table and subtables                                                                *
*--------------------------------------------------------------*/

#define STRIS_HELP_TABLE                555                                                     // ID der HelpTable Ressource

// Manual

#define HELP_GENERAL                    1000

#define HELP_COPYRIGHT                  2000
#define HELP_DISCLAIMER                 2100
#define HELP_AUTHOR                                     2200
#define HELP_CREDITS                    2300
#define HELP_INSTALLATION               3100
#define HELP_UNINSTALLING               3300
#define HELP_HOWTOPLAY                  4000
#define HELP_KEYS                                               4100
#define HELP_BUGS                                               5000
#define HELP_REVISIONS                  6000


// Subpanels

#define HELP_OPTIONS                    11000
#define HELP_HISCORE                    12000
#define HELP_ENTER_HISCORE              13000
#define HELP_KEYDIALOG                  14000



// Commonly used help-pages

#define HELP_EMPTY_PAGE                 32000




#define LabelBitmap 1000
#define GB_SETTINGS 107
#define DLG_ABOUT 16402
#define DLG_REGISTRATION 16478
#define RegisterHelpSubTable 16482
#define HELP_REGISTRATION 16000
#define GRB_TEST1 32002
#define DLG_UNREGISTERED 32005
#define UnregHelpSubTable 32010
#define DLG_SHOWHISCORE 1002
#define DLG_ENTERNAME 1004
#define DLG_KEY 1007

#define OptionsDialog 16403
#define PB_REGISTER 32016
#define IDF_REGISTER 32017
#define IDD_REGNAME 16480
#define PB_CODE 32018
#define IDD_USERNAME 32020
#define HELP_REGISTRATION_DLG 15000
#define IDF_HELPINDEX 32035
#define GRB_DROP 32038
#define RotateLeftBitmap 32040
#define TestBitmap 32041
#define BMP_DROP 32042
#define BMP_LEFT 32043
#define BMP_RIGHT 32044
#define BMP_ROTATELEFT 32045
#define BMP_ROTATERIGHT 32047
